# Docker configuration backend
providers:
    file:
        directory: /app/docker/quick-start
        watch: true

# API and dashboard configuration
api:
    insecure: false
    dashboard: false

entryPoints:
    web:
        address: ":80"

log:
    level: DEBUG

